/**
 * Every Ticketmaster venue the gazetteer places in Simcoe County, for the ticketmaster source.
 *
 * Ticketmaster's radius search misses venues it should find (Sadlon Arena, see
 * packages/adapters/src/ticketmaster.ts), so the source asks for events by venue id. Found
 * 2026-09-15 by listing Ticketmaster's venues within 90 km of Midhurst (308) and keeping the
 * 63 whose city, address or name resolves to a Simcoe municipality. Only two had
 * events on sale that day, Sadlon Arena and Casino Rama; the rest are listed so a venue that
 * starts selling needs no edit. A venue new to Ticketmaster does — repeat the survey.
 */
export const TICKETMASTER_VENUES: ReadonlyArray<{ id: string; name: string; municipality: string }> = [
  { id: "KovZpZAFltlA", name: "Loretto Tavern", municipality: "adjala-tosorontio" },
  { id: "KovZpZAdI7nA", name: "*Venues Vary By Concert*", municipality: "barrie" },
  { id: "KovZpZAkl7FA", name: "Army Navy and Air Force Club", municipality: "barrie" },
  { id: "KovZ917AL-i", name: "Attic Lounge at Flying Monkeys Craft Brewery", municipality: "barrie" },
  { id: "KovZpZAFItdA", name: "Barrie Central Collegiate", municipality: "barrie" },
  { id: "KovZpZAFI1dA", name: "Collier Street United Church", municipality: "barrie" },
  { id: "KovZpZAFEkdA", name: "Fendley Hall", municipality: "barrie" },
  { id: "rZ7HnEZ17fva4", name: "Ferndale Banquet Hall", municipality: "barrie" },
  { id: "KovZpak2je", name: "Foundation Night Club", municipality: "barrie" },
  { id: "KovZpZAFIFtA", name: "Georgian College - Athletic Centre", municipality: "barrie" },
  { id: "KovZpZAJldJA", name: "Georgian Theatre (formerly known as Gryphon Theatre)", municipality: "barrie" },
  { id: "KovZpZAFltnA", name: "Heritage Park", municipality: "barrie" },
  { id: "KovZpZAdIdvA", name: "Hi-Way Pentecostal Church", municipality: "barrie" },
  { id: "KovZ917AL-U", name: "Homestead Bakery & Cafe", municipality: "barrie" },
  { id: "KovZpZAFtvAA", name: "Kenzington", municipality: "barrie" },
  { id: "KovZpZA6vIvA", name: "Liberty North", municipality: "barrie" },
  { id: "KovZ917AL-C", name: "Meridian Place", municipality: "barrie" },
  { id: "KovZpZAkIt1A", name: "Roxy Side Room", municipality: "barrie" },
  { id: "KovZpZAFlv7A", name: "Sadlon Arena", municipality: "barrie" },
  { id: "KovZpZA7dlEA", name: "Sound Empire", municipality: "barrie" },
  { id: "KovZpZAk6lkA", name: "SPLASH CANYON WATER PARK", municipality: "barrie" },
  { id: "KovZ917AL-x", name: "St Andrews Church", municipality: "barrie" },
  { id: "KovZ917AL-b", name: "Temple Lounge at Donaleigh's Irish Public House", municipality: "barrie" },
  { id: "KovZpZAJdaaA", name: "The Fox", municipality: "barrie" },
  { id: "KovZpZAFEIAA", name: "The Mansion Night Club", municipality: "barrie" },
  { id: "KovZpZAkkEJA", name: "Traffic Lounge", municipality: "barrie" },
  { id: "KovZpZAFtvkA", name: "W. A. Fisher Auditorium", municipality: "barrie" },
  { id: "KovZpaKw1e", name: "Great Northern Exhibition Fairgrounds", municipality: "clearview" },
  { id: "rZ7HnEZ17feAg", name: "Osprey Community Centre", municipality: "clearview" },
  { id: "KovZpZAEdk1A", name: "All Saints Anglican Church", municipality: "collingwood" },
  { id: "KovZpZAkEJaA", name: "Collingwood Curling Club", municipality: "collingwood" },
  { id: "KovZ917ARgj", name: "Creemore Arena", municipality: "collingwood" },
  { id: "KovZpZAkE17A", name: "Fisher Field", municipality: "collingwood" },
  { id: "KovZpZAFtEkA", name: "Kaytoo Restaurant & Bar", municipality: "collingwood" },
  { id: "KovZ917ARoe", name: "Meaford & St. Vincent Community Centre & Arena", municipality: "collingwood" },
  { id: "KovZpaKRne", name: "Meaford Fairgrounds", municipality: "collingwood" },
  { id: "KovZpZAdIFnA", name: "Millennium Park", municipality: "collingwood" },
  { id: "KovZpZAdte6A", name: "Rusty's At Blue", municipality: "collingwood" },
  { id: "KovZpZAdIAvA", name: "Simcoe Street Theatre", municipality: "collingwood" },
  { id: "KovZpak2Fe", name: "Angus Glen Golf Club", municipality: "essa" },
  { id: "KovZ917ARiU", name: "Angus Recreation Centre Gym", municipality: "essa" },
  { id: "rZ7HnEZ17f8AP", name: "Essa Agriplex", municipality: "essa" },
  { id: "KovZpZAJdnAA", name: "Georgian Bay Steam Auto Gas and Antique Grounds", municipality: "innisfil" },
  { id: "KovZpZAkklIA", name: "Innisfil Recreation Complex", municipality: "innisfil" },
  { id: "KovZpZAFneaA", name: "Alliston Bandshell", municipality: "new-tecumseth" },
  { id: "KovZpZAEAJkA", name: "Alliston Memorial Arena", municipality: "new-tecumseth" },
  { id: "KovZpZAJFdJA", name: "Encore", municipality: "orillia" },
  { id: "KovZpaKRGe", name: "ODAS Park", municipality: "orillia" },
  { id: "KovZpZAkIetA", name: "Orillia Opera House", municipality: "orillia" },
  { id: "KovZpZAFlvtA", name: "Burl's Creek Event Grounds", municipality: "oro-medonte" },
  { id: "KovZ917A0ji", name: "Sunset Barrie - Part of Premier Theatres", municipality: "oro-medonte" },
  { id: "KovZpafKBe", name: "Sunset Barrie Drive-In Theatre", municipality: "oro-medonte" },
  { id: "KovZ917ARoO", name: "Penetanguishene Memorial Community Centre Arena", municipality: "penetanguishene" },
  { id: "KovZpZAdEEkA", name: "Casino Rama Resort", municipality: "ramara" },
  { id: "KovZpZAkkFEA", name: "J.B. Tudhope Memorial Park", municipality: "ramara" },
  { id: "KovZpZAkAn7A", name: "Odas Park", municipality: "severn" },
  { id: "KovZpaf73e", name: "Enaahtig Healing Lodge & Learning Centre", municipality: "tay" },
  { id: "KovZpZAkEa1A", name: "Dardanella", municipality: "wasaga-beach" },
  { id: "KovZ917AYdh", name: "Glenwood Drive Pop Up Park", municipality: "wasaga-beach" },
  { id: "KovZ917AYdo", name: "RecPlex", municipality: "wasaga-beach" },
  { id: "KovZ917AYdp", name: "Wasaga Sports Park", municipality: "wasaga-beach" },
  { id: "KovZ917AYdG", name: "Wasaga Stars Arena", municipality: "wasaga-beach" },
  { id: "KovZpafqJe", name: "WasagaDome", municipality: "wasaga-beach" },
]
